
# Suffix for temp files generated by redirect before being moved into place
RT=.redir-gen.tmp

JSON_ALL=elements-all.json
# The direct result of splitting JSON_ALL
ELEMENTS_TEMP_DIR=.tmp.elements
# A clone of the above with timestamps reflecting only actual changes
ELEMENTS_DIR=elements
# Discorporate SVG files containing individual pseudo-stroke shapes
LOOSE_SHAPES_DIR=loose-shapes
# Metadata included in the loose SVGs, combined with the original elements
EXT_META_DIR=ext-meta
# Aggregated ext-meta
EXT_META_ALL=ext-meta-all.json
# SVG files with loose shapes unioned together
UNIONED_SHAPES_DIR=unioned-shapes
UNIONED_SHAPES_TEMP_DIR=.tmp.unioned-shapes
TIGHT_SHAPES_DIR=tight-shapes
# FontForge project
FONTFORGE_PROJECT=project.sfd

# Home dir when running Inkscape
# (NB: The .tmp suffix is because make gets confused when the dir has the same name under both source and build dirs.)
INKSCAPE_CONTEXT_DIR=inkscape-context.tmp

DEFINE_ELEMENT_FILES=element-files.dep

all: tight

$(ELEMENTS_DIR): $(JSON_ALL)
	rm -rf $(ELEMENTS_TEMP_DIR)
	mkdir -p $(ELEMENTS_TEMP_DIR)
	../split-char-data.pl $(ELEMENTS_TEMP_DIR) $^
	@# Update only the changed elements to prevent spurious rebuilds.
	@# (rsync by checksum instead of time.)
	@# (-rlpgoD instead of -a: We don't want to update times on unchanged files.)
	rsync -rlpgoD --delete --checksum $(ELEMENTS_TEMP_DIR)/ $@/
	rm -rf $(ELEMENTS_TEMP_DIR)

# Generate a makefile include for the element file list
$(DEFINE_ELEMENT_FILES): $(ELEMENTS_DIR)
	+@echo -n "ELEMENT_FILES =" > $@$(RT)
	+@find $< -type f -name 'char-*.json' -print0 | sort -z | xargs -0 -i echo -n " {}" >> $@$(RT)
	+@echo "" >> $@$(RT)
	mv $@$(RT) $@

-include $(DEFINE_ELEMENT_FILES)

LOOSE_SHAPE_FILES=$(ELEMENT_FILES:$(ELEMENTS_DIR)/%.json=$(LOOSE_SHAPES_DIR)/%.svg)
EXT_META_FILES=$(ELEMENT_FILES:$(ELEMENTS_DIR)/%.json=$(EXT_META_DIR)/%.json)
UNIONED_SHAPE_FILES=$(ELEMENT_FILES:$(ELEMENTS_DIR)/%.json=$(UNIONED_SHAPES_DIR)/%.svg)
TIGHT_SHAPE_FILES=$(ELEMENT_FILES:$(ELEMENTS_DIR)/%.json=$(TIGHT_SHAPES_DIR)/%.svg)

# Prevent auto-delete of intermediates
.SECONDARY: $(ELEMENT_FILES) $(LOOSE_SHAPE_FILES) $(UNIONED_SHAPE_FILES) $(TIGHT_SHAPE_FILES) $(EXT_META_FILES)

.PHONY: tight clean-tight unioned loose extract-ext-meta ext-meta-all inkscape-context-dir

tight: $(TIGHT_SHAPE_FILES)

clean-tight:
	rm -rf $(TIGHT_SHAPES_DIR)

unioned: $(UNIONED_SHAPE_FILES)

loose: $(LOOSE_SHAPE_FILES)

extract-ext-meta: $(EXT_META_FILES)

ext-meta-all: $(EXT_META_ALL)

fontforge-project: $(FONTFORGE_PROJECT)

inkscape-context-dir: $(INKSCAPE_CONTEXT_DIR)

$(EXT_META_ALL): $(EXT_META_FILES)
	../json-files-to-array.sh $^ > $@$(RT)
	mv $@$(RT) $@

$(FONTFORGE_PROJECT): $(EXT_META_ALL) ../generate-font-project.py $(TIGHT_SHAPE_FILES)
	../generate-font-project.py < $< > $@$(RT)
	mv $@$(RT) $@

$(ELEMENT_FILES): | $(ELEMENTS_DIR)

$(INKSCAPE_CONTEXT_DIR): inkscape-context
	cp -vR "$<" "$@"

$(LOOSE_SHAPES_DIR):
	+@[ -d $@ ] || mkdir -p $@

$(EXT_META_DIR):
	+@[ -d $@ ] || mkdir -p $@

$(TIGHT_SHAPES_DIR):
	+@[ -d $@ ] || mkdir -p $@

$(UNIONED_SHAPES_DIR):
	+@[ -d $@ ] || mkdir -p $@

$(UNIONED_SHAPES_TEMP_DIR):
	+@[ -d $@ ] || mkdir -p $@

$(LOOSE_SHAPES_DIR)/%.svg: $(ELEMENTS_DIR)/%.json ../element-to-loose-svg.pl | $(LOOSE_SHAPES_DIR)
	PERL5LIB=../ ../element-to-loose-svg.pl < $< > $@$(RT)
	mv $@$(RT) $@

$(EXT_META_DIR)/%.json: $(ELEMENTS_DIR)/%.json $(LOOSE_SHAPES_DIR)/%.svg | $(EXT_META_DIR)
	echo -n '' > $@$(RT)
	echo '{' >> $@$(RT)
	echo $(word 2,$^) | perl -p -E 's!^.*\/(.*)\..*?$$!"file_basename":"$$1",!' >> $@$(RT)
	echo '"loose":' >> $@$(RT)
	perl -n -E 'while(/\G.*?<!--\[STFGMETA\[(.*?)\]STFGMETA\]-->/g) { say $$1; }' < $(word 2,$^) >> $@$(RT)
	echo ',' >> $@$(RT)
	echo '"element":' >> $@$(RT)
	cat $< >> $@$(RT)
	echo '}' >> $@$(RT)
	mv $@$(RT) $@

$(UNIONED_SHAPES_DIR)/%.svg: $(LOOSE_SHAPES_DIR)/%.svg inkscape-context-dir | $(UNIONED_SHAPES_DIR) $(UNIONED_SHAPES_TEMP_DIR)
	@# $(RT) not used here because Inkscape considers the suffix important
	@$(eval UNIONED_SHAPE_TEMP := $(UNIONED_SHAPES_TEMP_DIR)/$(notdir $@))
	cp $< $(UNIONED_SHAPE_TEMP)
	HOME="`pwd`"/$(INKSCAPE_CONTEXT_DIR) inkscape --verb EditSelectAllInAllLayers --verb SelectionUnion --verb FileSave --verb FileQuit $(UNIONED_SHAPE_TEMP)
	mv $(UNIONED_SHAPE_TEMP) $@

$(TIGHT_SHAPES_DIR)/%.svg: $(UNIONED_SHAPES_DIR)/%.svg | $(TIGHT_SHAPES_DIR)
	scour -i $< -o $@

